version: '3'
volumes:
  ark:
  steam:
services:
  ark:
    image: jkread/arkserver:latest
    container_name: ark
    network_mode: bridge
    restart: always
    ports:
      - 7777:7777
      - 7777:7777/udp
      - 7778:7778
      - 7778:7778/udp
      - 27015:27015
      - 27015:27015/udp
    volumes:
      - ark:/ark
      - steam:/home/steam
    environment:
      - Europe/Germany
      - am_ark_SessionName=Ark Docker Session
      - am_serverMap=TheIsland
      - am_ark_ServerPassword=letmein
      - am_ark_ServerAdminPassword=pleasechangeme
      - am_ark_MaxPlayers=70
      - am_ark_QueryPort=27015
      - am_ark_Port=7778
      - am_ark_RCONPort=32330
      - am_arkwarnminutes=15
      - am_arkAutoUpdateOnStart=true
      - am_arkBackupPreUpdate=true
      - am_arkMaxBackupSizeMB=500
      - am_arkflag_crossplay=false
      - am_arkflag_NoBattlEye=true
      - am_ark_GameModIds=111111111,566885854,731604991,761535755,821530042,889745138,1404697612
